x-kafka-defaults: &kafka-defaults
  build: .
  networks:
    - kafka-net
x-environment: &kafka-common-env
    KAFKA_REPLICATION_FACTOR: 3
    KAFKA_NUM_PARTITIONS: 3
    KAFKA_MIN_INSYNC_REPLICAS: 2
    KAFKA_CLUSTER_ID: "my-unique-cluster-id"
    KAFKA_CONTROLLER_QUORUM: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
    KAFKA_PORT: 9092
    KAFKA_CONTROLLER_PORT: 9093

services:
  kafka1:
    <<: *kafka-defaults
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      <<: *kafka-common-env
      KAFKA_HOST: kafka1
      NODE_ID: 1
    volumes:
      - kafka1_data:/tmp/kraft-combined-logs

  kafka2:
    <<: *kafka-defaults
    container_name: kafka2
    ports:
      - "9094:9092"
      - "9095:9093"
    environment:
      <<: *kafka-common-env
      KAFKA_HOST: kafka2
      NODE_ID: 2
    volumes:
      - kafka2_data:/tmp/kraft-combined-logs

  kafka3:
    <<: *kafka-defaults
    container_name: kafka3
    ports:
      - "9096:9092"
      - "9097:9093"
    environment:
      <<: *kafka-common-env
      KAFKA_HOST: kafka3
      NODE_ID: 3
    volumes:
      - kafka3_data:/tmp/kraft-combined-logs

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:

networks:
  kafka-net:
    driver: bridge